python scripts/create_synthetic_cascades_thresholds.py

#python scripts/set_multiscales_model_softcascade.py -i Prohibitive_trained_model_multiscales.proto.bin -t synthetic_cascades_thresholds.txt -o Prohibitive_multiscales_model_with_softcascade.proto.bin
python scripts/set_multiscales_model_softcascade.py -i Danger_trained_model_multiscales.proto.bin -t synthetic_cascades_thresholds.txt -o Danger_multiscales_model_with_softcascade.proto.bin
#python scripts/set_multiscales_model_softcascade.py -i Mandatory_trained_model_multiscales.proto.bin -t synthetic_cascades_thresholds.txt -o Mandatory_multiscales_model_with_softcascade.proto.bin
